name: 24h Auto Refresh
on:
  schedule:
    - cron: '0 0 * * *' # هەموو ٢٤ کاتژمێر جارێک
  workflow_dispatch: # بۆ ئەوەی ئێستا تاقی بکەیتەوە
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Refresh all plists
        run: |
          for file in *.plist; do
            echo "" >> "$file"
          done
      - name: Save Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automated daily refresh"
          git push
